### ISSUE TITLE
python-mpd2 v3.0 break daemon mode

### ISSUE THREAD

**Issue by Tokariew** [axujen/mpdrandom#10]
```
Press Enter to skip the current album.
Playing album "Krzysztof Wierzynkiewicz & Michał Cielecki & Adam Skorupa - Shadow Warrior (Original Soundtrack)".
Traceback (most recent call last):
  File "/home/tokariew/.local/bin/mpdrandom", line 8, in <module>
    sys.exit(main())
  File "/home/tokariew/.local/lib/python3.9/site-packages/lib/mpdrandom.py", line 176, in main
    client.idleloop(lib=args.library, clear=args.clear)
  File "/home/tokariew/.local/lib/python3.9/site-packages/lib/mpdrandom.py", line 114, in idleloop
    self.send_idle('player')
AttributeError: 'Client' object has no attribute 'send_idle'
```

With version 3.0 of python-mpd2 send_idle command was removed, breaking daemon mode

**Comment by cbumae** [comment]
Thanks for reporting this. As a short term fix we could revert
3f817ef6d38a3cea7c71debc4b7cd8a90d37b03a Skip an album in deamon mode

This removes the feature again to skip an album in daemon mode. But I like this feature so I will try to fix this by using the asyncio feature of the mpd library instead. But this requires changes in the whole script unfortunately.
