### ISSUE TITLE
Update to Python 3

### ISSUE THREAD

**Issue by Emgalai** [axujen/mpdrandom#2]
Python 2.7 will stop receiving support after January 1, 2020
https://pythonclock.org/

**Comment by axujen** [comment]
ok, i will see if i can get around to it soon. thanks for the heads up.

**Comment by therion23** [comment]
I changed all references in a "git pull" from python2.7 to python3 and then "sudo python3 setup.py install", and it works just fine in my setup.

Caveat emptor - works for me.

**Comment by cbumae** [comment]
Switch to python3 done in #5.
