### ISSUE TITLE
Match of every same titled album

### ISSUE THREAD

**Issue by therion23** [axujen/mpdrandom#7]
Greetings! When it happens that mpdrandom picks an album, it will queue every single album in your database which has the same title. Normally this would just be sort of funny, but if mpdrandom chooses "Greatest Hits" or "The Singles", it will queue every single album in your collection with the same title.

Anything to do about that?

**Comment by axujen** [comment]
im not sure, maybe its possible to make it  use other tags such as artist and year to handpick. but to be honest i haven't programmed in a long time and im not sure if i can do it myself. if someone else wants to open a pull request ill review it and merge.
i dont even have a proper music library anymore to test with either :/

**Comment by axujen** [comment]
The specific function to look at is [self.play_random()](https://github.com/axujen/mpdrandom/blob/0658b2d039b06b538817bad307f9ca384aacc144/lib/mpdrandom.py#L87)

i can take a shot at it but i dont have a way to test it

**Comment by therion23** [comment]
Artist would not be a good match - if a single artist album shares album title with a soundtrack or compilation, you might end up with one song. Not everybody use MusicBrainz ID's either, so my best idea is matching with MPD's internal pathnames.

My knowledge of Python is absolutely non existent, so hopefully some kind soul out there will give it a try?

**Comment by axujen** [comment]
the pathname would be a good idea but assuming the albums are organized properly. honestly now that i think about it theres no perfect way to do it, it all depends on the tagging. if paths aren't available we can mix albumname + albumartist + year

**Comment by axujen** [comment]
im closing this since no one is interested in doing it, i can't think of an elegant way to do it.

**Comment by therion23** [comment]
Yeah do so - thought about it quite a lot and never figured it out either. Guess there is no way of doing that without making assumptions about folder structure.

Thanks for giving it thought, and sorry for asking the impossible (unless proven otherwise) hehe.
